### ISSUE TITLE
Livre de compte - Ajout d'une zone "règlement"

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#11]
Ajout d'un formulaire pour "lettrer" les factures.

Proposition : 
On clique sur un bouton "règlement" d'une facture "non lettré/non réglé". Dans le formulaire qui s'ouvre, on à le choix : 
- Date de règlement
- Mode de paiement (virement - chèque - autres)
- type (Payées par le mandataire, payées directement par la formation politique, concours en nature)

Autre proposition : 
Rajouter ses champs directement quand on saisie une facture ou que l'on transfert un devis en facture, un seul champ de règlement vide indiquant une facture non réglé

**Comment by farlistener** [comment]
> type (Payées par le mandataire, payées directement par la formation politique, concours en nature)

Tu as des codes ? 😸

**Comment by Farocs** [comment]
DA
dépenses payées par le mandataire
DB
dépenses payées par les formations politiques
DC
concours en nature

Cela correspondra chaque fois à une colonne sur le compte de campagne

**Comment by farlistener** [comment]
Du coup avec DB et DC il faut aussi des lignes comptables en crédit, non ?

**Comment by Farocs** [comment]
Dépenses payées par les formations politiques :
Le total de la colonne DB doit correspondre à celui de la colonne RB.
Concours en nature :
Le total de la colonne DC doit correspondre à celui de la colonne RC.

**Comment by farlistener** [comment]
Donc : 
- dans le cas d'un DB, j'ai une recette  7032 
- dans le cas d'un DC, j'ai une recette  7050 ou 7051 ou 7052

il va falloir que je rajoute le choix
