### ISSUE TITLE
Affiliations - Ajout de fonctionnalités

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#12]
- Afficher les demandes et la liste des affiliés sous forme de liste
- Pouvoir classer les demandes et affiliations par templates [voir ticket 4](https://github.com/PartiPirate/gerermacampagne/issues/4)
- Pouvoir annuler une affiliations

**Comment by Farocs** [comment]
Rajout : 
- Pouvoir faire un mailing à tout les candidats
- Gérer les demandes des candidats [voir ticket 15](https://github.com/PartiPirate/gerermacampagne/issues/15)
- Avoir une vision simple, graphique, de l'état d'avancement des obligations minimal d'un candidat

**Comment by farlistener** [comment]
Tu peux splitter les points ?

**Comment by Farocs** [comment]
Point splitté, tu peux clore :)
