### ISSUE TITLE
Coordonnées Mandataire et expert comptable

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#13]
Mandataire : 
Identification du compte bancaire donc : 
- intitulé du compte
- N° de compte
- Nom de l'agence
- Adresse de l'agence
- Code postal
- Ville
- Date d'ouverture
  Pièce jointe à stocker : RIB

Pour l'expert comptable : 
Il faut une fiche d'identification avec : 
- Nom ou dénomination sociale
- Nom du représentant de la société d'expertise
- Inscrit au tableau de
- Adresse
- Code Postal
- Ville
- Téléphone
- Télécopie
- Courriel

**Comment by farlistener** [comment]
Pour le mandataire tu parles des informations comptes de campagne. Et pour cela il y a une tâche, qu'il faut donc enrichir.

Pour l'expert comptable, j'ai rajouté un type d'acteur expert-comptable, du coup il y a toutes les informations qui sont demandées sauf : 
- Nom ou dénomination sociale
- Inscrit au tableau de
- Téléphone
- Télécopie

L'ajout d'un expert comptable devrait valider automatiquement la tâche "search_chartered_accountant" (si existante ou par ajout cause don / facture)

**Comment by Farocs** [comment]
Ok, il faut donc une tâche "chercher un expert comptable" si mouvement financier (voir avant avec explication).
Cette tâche ne devraient pouvoir être validé que si on a renseigner les coordonnée de base de l'expert comptable.
A partir de ce moment la, une nouvelle tâches doit s'ouvrir qui demande les informations supplémentaire (moins urgent) qui ne doit disparaitre qu'à la saisie de ses informations (ou ?)

**Comment by farlistener** [comment]
Alors :
- Plus de données dans le formulaire de création d'acteurs
- L'expert comptable remplace la notion de "pseudo" par "raison sociale"
- Quand on veut "finaliser" la recherche d'un expert comptable, ça lance le formulaire d'ajout expert comptable
- L'ajout d'un expert comptable finalise la recherche d'un expert comptable
- La tâche fraîchement ajoutée de recherche d'expert comptable est automatiquement finalisée si un expert comptable est déjà renseigné
