### ISSUE TITLE
procédure d'installation

### ISSUE THREAD

**Issue by ghost** [PartiPirate/gerermacampagne#18]
Bonjour,

Ou puis-je trouver une procédure d'installation ?

Merci pour ce travail :-)

**Comment by farlistener** [comment]
Il faut que je fasse ça

**Comment by ghost** [comment]
Je peux aider à rédidger ça avec quelque pointeurs :-)

Le fichier dans lequel est le schéma de la base de donnée par exemple: en cherchant "create table" je n'ai pas trouvé mais peut-être qu'il y a un ORM ? 

Une autre possibilité pour que je puisse contribuer à la doc d'installation serait de savoir quelle base logicielle a été utilisée pour démarrer le projet. En la consultant j'aurais probablement d'autres indices.

**Comment by ghost** [comment]
@farlistener merci d'avoir rajouté le schéma de la base. Je ne l'ai pas vu parceque je n'observais pas tout le projet. C'est fait maintenant :-) Je vais essayer de créer une instance et je rajoute mes problèmes éventuels ici :-)

**Comment by ghost** [comment]
Le début des instructions d'installation:

<pre>
Sur une Ubuntu 16.04
sudo apt-get install libapache2-mod-php7.0 mysql-server apache2
cd /var/www/html
git clone https://github.com/partipirate/gerermacampagne.git
mysqladmin -u root -p create gerermacampagne
mysql -u root -p gerermacampagne < gerermacampagne/public/create.sql
cat > gerermacampagne/application/config/config.php <<'EOF'
&lt;?php
$config = array();
$config["database"]["database"] = "gerermacampagne";
$config["database"]["host"] = "localhost";
$config["database"]["port"] = "3306";
$config["database"]["login"] = "root";
$config["database"]["password"] = "abc";
?>
EOF
</pre>

Il y a quelque chose qui tourne maintenant :-) 

http://149.202.182.63/gerermacampagne/application/about.php

Mais je ne suis pas sur de ce que je dois faire ensuite. Dans le fichier database.php je vois

```
include_once("config/salt.php");
```

mais ce fichier n'existe pas dans le repository. Est-ce qu'il y a des fichiers qui permettent de faire un déploiement avec salt quelque part ?

Merci de ton aide !

**Comment by farlistener** [comment]
Alors, pour d'autres projets qui tournent sur la même "infra" et pile technique j'ai une page de configuration, il faut juste que je l'importe (et du coup c'était prévu) et ça évite notamment la dernière commande

Ensuite clairement il faut que je change cette page about :D 

Dans le salt.php

<?php
if(!isset($config)) {
    $config = array();
}

$config["base_url"] = "http://149.202.182.63/gerermacampagne/";
$config["default_language"] = "fr";
$config["salt"] = "123456789";
$config["cron_enabled"] = 1;
$config["document_directory"] = "documents/";
?>

Et faudrait que j'architecture mieux les fichiers de conf (là on sent que ça a débordé)

**Comment by farlistener** [comment]
Clairement le dernier commit n'apporte la gestion du salt.php (pour l'instant)

En revanche si tu rajoutes dans ton config.php les trois lignes suivantes (en changeant les info #CaptainObvious) : 

$config["administrator"] = array();
$config["administrator"]["login"] = "captain";
$config["administrator"]["password"] = "obvious";

Tu auras accès à la page, c'est peut-être la conf minimale à mettre

**Comment by ghost** [comment]
J'ai mis à jour avec ces information:

<pre>
Sur une Ubuntu 16.04
sudo apt-get install libapache2-mod-php7.0 mysql-server apache2
cd /var/www/html
git clone https://github.com/partipirate/gerermacampagne.git
mysqladmin -u root -p create gerermacampagne
mysql -u root -p gerermacampagne < gerermacampagne/public/create.sql
cat > gerermacampagne/application/config/config.php <<'EOF'
&lt;?php
$config["database"]["database"] = "gerermacampagne";
$config["database"]["host"] = "localhost";
$config["database"]["port"] = "3306";
$config["database"]["login"] = "root";
$config["database"]["password"] = "abc";
$config["administrator"] = array();
$config["administrator"]["login"] = "captain";
$config["administrator"]["password"] = "obvious";
?>
EOF
cat > gerermacampagne/application/config/salt.php <<'EOF'
&lt;?php
if(!isset($config)) {
$config = array();
}
$config["base_url"] = "http://149.202.182.63/gerermacampagne/";
$config["default_language"] = "fr";
$config["salt"] = "123456789";
$config["cron_enabled"] = 1;
$config["document_directory"] = "documents/";
?>
EOF
</pre>

et j'ai git pull pour être à bd96e32be0032eb44abc7b527cfd860e1dc1e85f. Note que j'ai gardé "captain" "obvious" mais je ne parviens pas à me logger (bloqué pour 10 minutes après plusieurs tentatives ;-).

J'ai essayé de charger la nouvelle page administration.php et je vois les messages suivant dans error.log de apache:

<pre>
[Sun Oct 02 08:22:10.828900 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: server in /home/ubuntu/gerermacampagne/application/administration.php on line 47
[Sun Oct 02 08:22:10.828961 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: server in /home/ubuntu/gerermacampagne/application/administration.php on line 56
[Sun Oct 02 08:22:10.828974 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: server in /home/ubuntu/gerermacampagne/application/administration.php on line 57
[Sun Oct 02 08:22:10.828988 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: server in /home/ubuntu/gerermacampagne/application/administration.php on line 58
[Sun Oct 02 08:22:10.829007 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: server in /home/ubuntu/gerermacampagne/application/administration.php on line 67
[Sun Oct 02 08:22:10.829014 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: server in /home/ubuntu/gerermacampagne/application/administration.php on line 68
[Sun Oct 02 08:22:10.829368 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: galette in /home/ubuntu/gerermacampagne/application/administration.php on line 119
[Sun Oct 02 08:22:10.829375 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: personae in /home/ubuntu/gerermacampagne/application/administration.php on line 127
[Sun Oct 02 08:22:10.829380 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: memcached in /home/ubuntu/gerermacampagne/application/administration.php on line 148
[Sun Oct 02 08:22:10.829401 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: memcached in /home/ubuntu/gerermacampagne/application/administration.php on line 153
[Sun Oct 02 08:22:10.829406 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 170
[Sun Oct 02 08:22:10.829409 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 175
[Sun Oct 02 08:22:10.829412 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 184
[Sun Oct 02 08:22:10.829432 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 185
[Sun Oct 02 08:22:10.829438 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 186
[Sun Oct 02 08:22:10.829455 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 199
[Sun Oct 02 08:22:10.829462 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 204
[Sun Oct 02 08:22:10.829477 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 212
[Sun Oct 02 08:22:10.829484 2016] [:error] [pid 11054] [client 77.180.190.228:51226] PHP Notice:  Undefined index: smtp in /home/ubuntu/gerermacampagne/application/administration.php on line 217
</pre>

Une idée ?

**Comment by ghost** [comment]
Peut-être que je peux essayer de renseigner les champs manquant, en lisant le code de la page d'administration pour savoir a quoi ils font référence ?

**Comment by ghost** [comment]
@farlistener le week-end est le meilleur moment pour discuter de ça ? Je suppose que, comme moi, tu as un travail dans la vraie vie ;-)

**Comment by farlistener** [comment]
A priori la page d'administration fonctionne correctement
