### ISSUE TITLE
Livre de Compte - Ajout de type de Recette

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#29]
On a pour le moment les recettes de 7010 à 7031. Il faut rajouter : 
7032 – dépenses payées directement par les formations politiques
7050 – concours en nature fournis par les candidats
7051 – concours en nature fournis par les formations politiques
7052 – concours en nature fournis par les personnes physiques
7580 – produits divers
7600 – produits financiers

Note : on a toujours 3 colonnes dans le compte de campagne.
Les dépenses 7010 à 7031 vont dans la colonne RA
la dépense 7032 dans la colonne RB
7050-7052 dans la colonne RC
7580-7600 dans la colonne RA

Descriptif des colonnes : 
RA
Recettes
versées au compte du mandataire
RB
Paiement par les formations politiques
RC
Concours en nature

**Comment by Farocs** [comment]
Concernant les comptes 7026 et 7027 (Montant des frais financiers payés directement par le candidat et Montant des menues dépenses payées directement par le candidat) il faut : 

- Que le détail apparaisse en annexe 3
- Le montant du compte 7026 doit correspondre au comptes 6613
- Le montant du compte 7027 doit correspondre au comptes 6789

**Comment by farlistener** [comment]
> - Le montant du compte 7026 doit correspondre au comptes 6613
> - Le montant du compte 7027 doit correspondre au comptes 6789

En français ça donne ?

**Comment by Farocs** [comment]
Le montant des frais financiers payés directement par le candidat  dans les dépenses (compte 6613) doit être égal au montant des frais financiers payés directement par le candidat dans les recettes (compte 7026).

Pareil avec le 6789 qui correspond au 7027

**Comment by farlistener** [comment]
Ce que je veux dire par là c'est que je n'ai pas, encore, les codes 6613 et 6789

**Comment by Farocs** [comment]
Oki, je viens de voir et c'est simplement que les comptes 6613-6789 n'apparaissent pas sur le compte de campagne ... Donc on oublie ses deux comptes, on maintient par contre le 7026 et 7027 qui devront apparaitre dans l'annexe 3

**Comment by Farocs** [comment]
6613 : Frais financiers payés directement par le candidat
6789 : Menues dépenses payées directement par le candidat
