### ISSUE TITLE
[PAGE AFFILIATIONS] - Renommage d'une campagne d'un candidat

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#32]
Il pourrait être utile de pouvoir renommer une campagne d'un candidat (standardisation de nommage ou assistance pour un candidat).

**Comment by farlistener** [comment]
Ainsi que pour la circonscription, non :smile_cat: ?

**Comment by farlistener** [comment]
A tout le moins, c'est possible de le faire pour les membres de la campagne
