### ISSUE TITLE
Créer des templates pour les campagnes nationales

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#4]
Plutôt que d'avoir un risque d'erreur lors de la création de sa campagne, il pourrait être utile d'avoir des modèles de campagne générique (législatives 2017 par exemple) permettant aux créateur de sa campagne de ne pas faire d'erreur.

**Comment by farlistener** [comment]
Il faut que j'étoffe un peu le système pour ça mais grosso modo c'est ce que le système permet
