### ISSUE TITLE
Permettre une synchronisation de la liste des tâches avec un calendrier

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#7]
Permettre une synchronisation de la liste des tâches avec un calendrier type ICS/Calendrier partagé ?

Idéalement un calendrier par type d'acteur ?

**Comment by farlistener** [comment]
Trois liens dispo en fin de page :
- Calendrier (avec toutes les tâches qui ont une date)
- Calendrier du candidat (avec toutes les tâches que peut valider un candidat)
- Calendrier du mandataire (avec toutes les tâches que peut valider un mandataire)
