### ISSUE TITLE
Livre de compte - Gestion des Devis

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/gerermacampagne#9]
Un devis ne doit pas être pris en compte dans le compte de campagne, mais dans une liste indépendante.
Le candidat peut faire faire plusieurs devis pour un seul problème
Le candidat peut décider de stocker l'ensemble des devis même s'il en a déjà choisi un
Cela permet au candidat d'apporter un devis et au suppléant un autre sur le même thème

Je propose donc une gestion des devis indépendante, fonctionnant de la manière suivante : 
1. Une liste des devis
2. Ajout d'un champ "catégorie" avec une liste "Fournitures/Location/Experts/comptable/transport/frais" que je détaillerais dans un ticket sur les factures (liste identique)
3. Possibilité de "transférer" un devis en facture (création d'un champ Facture dans le livre de compte, demande du PDF de la facture et liaison avec le devis initial"

**Comment by farlistener** [comment]
Les points 2 et 3 sont faits

**Comment by farlistener** [comment]
1/ Les devis ne sont pas séparés (et pour l'instant ne le seront pas). MAIS leurs montants ne sont plus comptabilisés
